### ISSUE TITLE
Google Search Engine option

### ISSUE THREAD

**Issue by tanmayb123** [brmson/yodaqa#49]
Along with Bing integration, I think it would be good to give the user the option to use Google or Bing, or maybe both at the same time?

**Comment by k0105** [comment]
From what I can tell pull requests are welcome.

**Comment by pasky** [comment]
@tanmayb123, we use Bing not out of love for Microsoft ;) but because it offers a developer API. Google Search has no such thing, as far as we know, which makes using it much more complicated and probably against the terms of service.  Therefore, I'm going to close this for now.

Feel free to reopen if we are wrong or open a pull request if you manage to get this to work. Thanks!

**Comment by tanmayb123** [comment]
But I use their developer (JSON) API in my iOS App: https://developers.google.com/custom-search/json-api/v1/overview#prerequisites
However, it is paid, they allow 100 free requests.
