### ISSUE TITLE
Labels service down

### ISSUE THREAD

**Issue by xteejx** [brmson/yodaqa#64]
Labels service is now down, along with the solr instance and dbpedia.

**Comment by pasky** [comment]
Hi!

  I just tested and everything seems to work.

  There actually was a problem - with the freebase fuseki instance,
which got stuck for unknown reasons and I restarted.

**Comment by xteejx** [comment]
That may be the contributing factor to the other issue report if it was hanging my end and timing out. Trying to run this on a regular PC isn't easy lol

**Comment by pasky** [comment]
Right, but it was hanging in CluesToConcepts, which hints more to
network connectivity issue.

**Comment by xteejx** [comment]
Agreed. Will close this (and the other) for now and reopen if it's still an issue tomorrow.

**Comment by nagygergo** [comment]
Hi!

Labels service seems to be down at http://yodaqa.felk.cvut.cz/dbp-labels1/ and it took down the demo pipeline (both the general and the movies one). Is it intentional or is it some kind of accident?  My own pipeline that I fiddle around with uses your backed, so if you can get it up and running, that would be great. Thanks :)
